const fs = require('fs')
const path = require('path')

const svgDir = path.join(__dirname)

fs.readdir(svgDir, (err, files) => {
  if (err) {
    console.error('Error reading directory:', err)
    return
  }

  const iconNames = files
    .filter(file => file.endsWith('.svg'))
    .map(file => `'${path.basename(file, '.svg')}'`)
    .join(',\n  ')

  const content = `// DO NOT EDIT THIS FILE
// This file is generated by the generateIconNames.js script to dynamically import the icon names
// It is automatically run when building the share app
// If needed, you can run the script manually with 'npm run generate-icon-names' in apps/share directory

export const names = [
  ${iconNames}
] as const
`

  fs.writeFile(path.join(__dirname, 'iconNames.ts'), content, err => {
    if (err) {
      console.error('Error writing file:', err)
    } else {
      console.log('Icon names generated successfully!')
    }
  })
})
