// DO NOT EDIT THIS FILE
// This file is generated by the generateIconNames.js script to dynamically import the icon names
// It is automatically run when building the share app
// If needed, you can run the script manually with 'npm run generate-icon-names' in apps/share directory

export const names = [
  'add',
  'checkmark',
  'close',
  'dice',
  'edit',
  'search',
  'undo'
] as const
